
# Bridge for camera data
#- ros_topic_name: "/drone_inspetor/externo/camera/image_raw"
#  gz_topic_name: "/drone_inspetor/gz/gimbal/camera"
#  ros_type_name: "sensor_msgs/msg/Image"
#  gz_type_name: "gz.msgs.Image"
#  direction: GZ_TO_ROS
#  qos_profile: SENSOR_DATA

# Bridge for depth camera data
#- ros_topic_name: "/drone_inspetor/externo/depth_camera/image_raw"
#  gz_topic_name: "/drone_inspetor/gz/depth_camera"
#  ros_type_name: "sensor_msgs/msg/Image"
#  gz_type_name: "gz.msgs.Image"
#  direction: GZ_TO_ROS
#  qos_profile: SENSOR_DATA

# Bridge for LIDAR data
- ros_topic_name: "/drone_inspetor/externo/lidar/scan"
  gz_topic_name: "/drone_inspetor/gz/lidar_2d_v2"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Bridge for LIDAR 1D inferior (ground distance - LW20)
- ros_topic_name: "/drone_inspetor/externo/lidar_down/scan"
  gz_topic_name: "/world/Plataforma_UERJ/model/x500_uerj_0/link/lidar_sensor_link/sensor/lidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Bridge for joint states (optional, for debugging)
- ros_topic_name: "/drone_inspetor/externo/joint_states"
  gz_topic_name: "/world/oceano/model/x500_uerj/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS



